kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
# set your lab user name
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
# set your lab user name
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: index-html
          configMap:
            name: index.html
            defaultMode: 420
      containers:
        - resources: {}
          env:
            - name: PORT
              value: {{ .Values.containers.containerPort | quote }}
          readinessProbe:
            {{- tpl (toYaml .Values.Probes.readiness) . | nindent 12 }}
            
          livenessProbe:
            {{- tpl (toYaml .Values.Probes.liveness) . | nindent 12 }}
            httpGet:
              port: {{ .Values.containers.containerPort }}
              
          volumeMounts:
            {{- tpl (toYaml .Values.volume.mountPath) . | nindent 12 }}
            - name: index-html

          terminationMessagePath: /dev/termination-log
          name: {{ .Release.Name }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: IfNotPresent
# update with the image you build in part 1
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
    #this will Create Volume From our ConfigMap

 