apiVersion: v1
kind: Secret
metadata:
  name: gh-details
type: Opaque
data:
  USERNAME: {{ .Values.github.user | b64enc }}
  TOKEN: {{ .Values.github.token | b64enc }} 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
  URL: {{ .Values.github.url | b64enc }} 