ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/hezis1/test'
  tag: 'chart_v2'

service:
  servicePort: 8080

probes:
  readiness:
      path: /health/readiness
      scheme: HTTP
    initialDelaySeconds: 1 # the time is waiting befor testing the application path
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
      path: /health/liveliness
      scheme: HTTP
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1 
    failureThreshold: 3
volume:
  mount:
    mountPath: /tmp/html # this will mount the html.index file to it application location

