ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/hezis1/test'
  tag: 'chart_v2'

service:
  servicePort: 8080

probes:
  readiness:
      path: /health/readiness
      httpGet:
        scheme: HTTP
        port: 8080 #{{ .Values.containers.containerPort  }} # In which port the Application is listening
    initialDelaySeconds: 1 # the time is waiting befor testing the application path
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
      path: /health/liveliness
      httpGet:
        scheme: HTTP
        port: 8080
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1 
    failureThreshold: 3
volume:
  mount:
    mountPath: /tmp/html # this will mount the html.index file to it application location

