ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/hezis1/test'
  tag: 'chart_v2'

service:
  servicePort: 8080

probes:
  readiness: 
    httpGet:
      scheme: HTTP
      port: 8080      
    path: /health/readiness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    httpGet:
      scheme: HTTP
      port: 8080     
      path: /health/liveliness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

volume:
  mount:
    path: /tmp/html

test: Healthy

github:
  user: hezis1
  token: empty-pass
  url: https://github.com/Hezis1/app-dev-lab


